### ISSUE TITLE
"IndexError: list index out of range" while trying to use the new version of the sensor

### ISSUE THREAD

**Issue by MikaSakari** [anand-p-r/fmi-hass-custom#24]
Hi, 
tried to install FMI component but I'm getting the following errors as seen at the bottom of this message. In this specific Rasperry Pi 3 I didn't have any earlier installations of FMI. I'm pretty sure I have followed exactly the instructions on how to install this custom component, but so far no success in fetching any measurements. Any idea what I'm doing wrong? 

(I also tried to upgrade the earlier version of the FMI sensor in a completely different RPi3, and experienced similar problems despite having cleared the cache according to the instructions)

I don't have any issues in using an earlier version of the sensor, though.

Thanks
BR, Mika

-->

2021-04-29 21:09:26 WARNING (MainThread) [homeassistant.loader] You are using a custom integration fmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-29 21:12:34 ERROR (MainThread) [custom_components.fmi] Unexpected error fetching fmi data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fmi/__init__.py", line 365, in _async_update_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fmi/__init__.py", line 335, in update_mareo_data
    if root_mareo[n][0][2].text == 'SeaLevel':
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 216, in __getitem__
    return self._children[index]
IndexError: list index out of range
2021-04-29 21:12:34 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Viitaila' for fmi integration not ready yet; Retrying in background
2021-04-29 21:12:43 ERROR (MainThread) [custom_components.fmi] Unexpected error fetching fmi data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fmi/__init__.py", line 365, in _async_update_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fmi/__init__.py", line 335, in update_mareo_data
    if root_mareo[n][0][2].text == 'SeaLevel':
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 216, in __getitem__
    return self._children[index]
IndexError: list index out of range
2021-04-29 21:12:57 ERROR (MainThread) [custom_components.fmi] Unexpected error fetching fmi data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fmi/__init__.py", line 365, in _async_update_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fmi/__init__.py", line 335, in update_mareo_data
    if root_mareo[n][0][2].text == 'SeaLevel':
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 216, in __getitem__
    return self._children[index]
IndexError: list index out of range
2021-04-29 21:13:20 ERROR (MainThread) [custom_components.fmi] Unexpected error fetching fmi data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fmi/__init__.py", line 365, in _async_update_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fmi/__init__.py", line 335, in update_mareo_data
    if root_mareo[n][0][2].text == 'SeaLevel':
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 216, in __getitem__
    return self._children[index]
IndexError: list index out of range
2021-04-29 21:14:04 ERROR (MainThread) [custom_components.fmi] Unexpected error fetching fmi data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fmi/__init__.py", line 365, in _async_update_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fmi/__init__.py", line 335, in update_mareo_data
    if root_mareo[n][0][2].text == 'SeaLevel':
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 216, in __getitem__
    return self._children[index]
IndexError: list index out of range
2021-04-29 21:15:27 ERROR (MainThread) [custom_components.fmi] Unexpected error fetching fmi data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fmi/__init__.py", line 365, in _async_update_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fmi/__init__.py", line 335, in update_mareo_data
    if root_mareo[n][0][2].text == 'SeaLevel':
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 216, in __getitem__
    return self._children[index]
IndexError: list index out of range
2021-04-29 21:16:52 ERROR (MainThread) [custom_components.fmi] Error requesting fmi data: HTTPConnectionPool(host='opendata.fmi.fi', port=80): Max retries exceeded with url: /wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi%3A%3Aforecast%3A%3Ahirlam%3A%3Asurface%3A%3Apoint%3A%3Amultipointcoverage&timestep=10&starttime=2021-04-29T18%3A06%3A47%2B00%3A00&endtime=2021-04-29T18%3A16%3A47%2B00%3A00&latlon=61.14532384470369%2C25.347302332520492 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x6a7a7898>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by anand-p-r** [comment]
@MikaSakari  Yes there was a bug with the index handling for the newly added sea level sensor. That is now corrected and additional debug logs have been added. Please try with the new [release](https://github.com/anand-p-r/fmi-hass-custom/releases/tag/v0.3.3).

**Comment by MikaSakari** [comment]
@anand-p-r Still failing, now the error seems to be slightly different.

-->

2021-04-30 19:36:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration fmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-30 19:38:25 ERROR (MainThread) [custom_components.fmi] Unexpected error fetching fmi data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fmi/__init__.py", line 368, in _async_update_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fmi/__init__.py", line 347, in update_mareo_data
    _LOGGER.debug("FMI: Mareo_data updated with data: %s %s", sealevel_tuple_list[0], sealevel_tuple_list[12])
IndexError: list index out of range
2021-04-30 19:38:25 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Viitaila' for fmi integration not ready yet; Retrying in background
2021-04-30 19:38:37 ERROR (MainThread) [custom_components.fmi] Unexpected error fetching fmi data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fmi/__init__.py", line 368, in _async_update_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fmi/__init__.py", line 347, in update_mareo_data
    _LOGGER.debug("FMI: Mareo_data updated with data: %s %s", sealevel_tuple_list[0], sealevel_tuple_list[12])
IndexError: list index out of range
2021-04-30 19:38:54 ERROR (MainThread) [custom_components.fmi] Unexpected error fetching fmi data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/fmi/__init__.py", line 368, in _async_update_data
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fmi/__init__.py", line 347, in update_mareo_data
    _LOGGER.debug("FMI: Mareo_data updated with data: %s %s", sealevel_tuple_list[0], sealevel_tuple_list[12])
IndexError: list index out of range

**Comment by anand-p-r** [comment]
@MikaSakari  As the saying goes - "Never fix anything on a Friday Evening" ;). Nevertheless, I have tried to fix another bug with the index check. Apparently the lat/long that you are using is not producing the expected results from the FMI API. But before I request you for the location details, I have tried to fix the issue in the latest [release](https://github.com/anand-p-r/fmi-hass-custom/releases/tag/v0.3.4). If this also breaks, I might need more details to debug the issue. But please give this a try and let me know. Have a good weekend and hyvä vappu!!

**Comment by MikaSakari** [comment]
@anand-p-r so far so good, no errors in the log and sensors became visible again. Yes I'm located quite deep inland so sea level is completely irrelevant - the whole country will be in deep trouble if my place will be next to seashore... Thanks for fixing. Have a nice Vappu !

**Comment by anand-p-r** [comment]
@MikaSakari Thanks! Will close the issue now.
